#! /bin/bash
#This screip will execute evry day on 23:59:00 and check for acounts expires
#If an account is expired, Then Lock it
log(){
	echo "$(date +'%b %d %T') [update_acc_expire] $1" >> /var/log/acc-expire.log
	echo "$1" 
}
log "acc_axpire_check run"
declare -A $(awk '{print "EXPIRE_DATES["$1"]="$2}' /etc/acc-expire/users)
DATE=$(date +%F)
for user in "${!EXPIRE_DATES[@]}"
do
	#check if user exists
	#if not remove the line contains not-exsisting user from /etc/acc-expire/users
	if ! id -u $user &>/dev/null; then
		log "User $user dose not exists, removing it from /etc/acc-expire/users"
		echo -e "$(grep -v -w "$user" /etc/acc-expire/users)" > /etc/acc-expire/users
		continue
	fi
	if [[ $(date +%s) -gt $(date +%s -d "${EXPIRE_DATES[$user]} 23:59:00 ") ]]; then
		 
		sudo usermod -L "$user"
		log "User $user was locked"
		bash /usr/local/bin/update_acc_expire -n "$user" -d ${EXPIRE_DATES[$user]}
		
	fi
done



