#! /bin/bash
USER_NAME=""
DATE=""
print_help(){
	echo "-n\t\tusen name"
	echo "-d\t\tThe date option, next expire date will calculate from given date"
	echo "-h\t\tto show this help"
} 
log(){
	echo "$(date +'%b %m %T') [update_acc_expire] $1" >> /var/log/acc-exipre.log
	echo "$1" 
}
#n is name of user
#d is date that must be claculated from it
#r is option for just recalculate expire date for next priod
while getopts ":n:d:rh" opt; do
	case $opt in
		n)
			USER_NAME="$OPTARG"
			;;
		d)
			DATE="$OPTARG"
			;;
		h)
			print_help
			exit 1
			;;
		\?)
			echo "Invalid option -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done
if [[ $USER_NAME ]]
then
	# user exists
	if ! id -u $USER_NAME &>/dev/null; then
		echo "User $USER_NAME dose not exists"
		exit 1
	fi
	if [[ ! $DATE ]]
	then
		DATE="Today"
	fi
	diffMinute=$(( ( $(date +%s) - $(date -d "$DATE 23:59:00 30 days" +%s) ) / 60 ))
	if [[ $diffMinute -gt 0 ]]; then
		#43200 is 30 days to minute
		remaining_minute=$(( 43200 - ($diffMinute % 43200) ))
		next_expire_date=$(date +%F -d "Today $remaining_minute minutes")
	else
		next_expire_date=$(date -d "$DATE 23:59:00 30 days" +%F)
	fi
	if grep -w $USER_NAME &>/dev/null; then
		sed -i "s/.*$USER_NAME.*/$USER_NAME $next_expire_date/" /etc/acc-expire/users
	else
		echo "$USER_NAME $next_expire_date" >> /etc/acc-expire/users
	fi
	log "Next expire date for user $USER_NAME was set to $next_expire_date"
else
	echo "You must spesify user name"
fi


