#!/bin/bash
read -p "Enter UserName : " user_name
read -p "Enter Password : " pass
read -e -p "Enter Group name [default is twologin] : " -i "twologin" group
group=${group:-"twologin"}
if ! getent group "$group"
then 
	groupadd "$group"
fi
if useradd "$user_name" -g "$group" -M
then
	echo -e "$pass\n$pass" | passwd "$user_name"
	bash /usr/local/bin/update_acc_expire -n "$user_name" 
fi

