#!/bin/bash
read -p "Enter UserName : " user_name
read -p "Enter Password : " pass
read -e -p "Enter Group name [default is twologin] : " -i "twologin" group
group=${group:-"twologin"}
if ! getent group "$group"
then 
	groupadd "$group"
fi
if useradd "$user_name" -g "$group" -M
then
	echo -e "$pass\n$pass" | passwd "$user_name"
	let expireDay=$(date +%d -d "Today +30 days")
	((crontab -l | grep -v -w "$user_name") ; echo "0 0 $expireDay * * usermod -L $user_name") | crontab -
fi

